### ISSUE TITLE
feat: `-f` flag

### ISSUE THREAD

**Issue by miller-time** [miller-time/hq#3]
currently `hq` assumes that the HCL input file is passed on stdin. theoretically, having a `-f` flag to specify the file(s) being operated on has a greater-than-zero chance of improving the `hq` quality of life

for command-line argument parsing, `hq` uses **clap** with the **derive** feature. the [git_derive](https://docs.rs/clap/latest/clap/_derive/_cookbook/git_derive/index.html) cookbook is a great reference for examples of how it works

**Comment by rcousineau-xandr** [comment]
perhaps even better than the `git_derive` cookbook I've always looked at... there's now a `derive` Reference!

https://docs.rs/clap/latest/clap/_derive/index.html
